<?php

return [
    'name' => 'Globos Sensacionales',
    'shipping' => 'Envíos a todo México',
    'whatsapp' => env('GLOBOS_WHATSAPP', '5210000000000'),
    'whatsapp_message' => 'Hola, me interesa ser distribuidor de Globos Sensacionales y conocer sus productos. Envíos a todo México.',
    'catalog_path' => env('GLOBOS_CATALOG_PATH', 'catalogo/catalogo-sensacional.pdf'),
    'catalog_view_url' => '/catalogo/2026/Catalogo-Sensacional-2026.php',
    'distributor_catalog_path' => env(
        'GLOBOS_DISTRIBUTOR_CATALOG_PATH',
        'distribuidores-cat/globos-distribuidores-ex.pdf',
    ),
    'distributor_catalog_hint' => 'Descarga aquí recursos descargables para distribuidores, pide con tu asesor tu contraseña personal para poder tener acceso a estas herramientas de venta especiales para tí.',
    'social' => [
        'instagram' => env('GLOBOS_INSTAGRAM', 'https://www.instagram.com/globos_sensacional/'),
        'facebook' => env('GLOBOS_FACEBOOK', 'https://www.facebook.com/SensacionalGlobos'),
        'pinterest' => env('GLOBOS_PINTEREST', 'https://mx.pinterest.com/globossensacional/'),
        'tiktok' => env('GLOBOS_TIKTOK', 'https://www.tiktok.com/@globossensacional'),
        'youtube' => env('GLOBOS_YOUTUBE', 'https://www.youtube.com/@GlobosSensacional'),
    ],
    'seo' => [
        'description' => 'Globos Sensacionales fabrica globos 100% de látex natural para distribuidores, decoradores y puntos de venta. Más de 30 años de experiencia. Envíos a todo México.',
    ],
    'states' => [
        'Aguascalientes',
        'Baja California',
        'Baja California Sur',
        'Campeche',
        'Chiapas',
        'Chihuahua',
        'Ciudad de México',
        'Coahuila',
        'Colima',
        'Durango',
        'Estado de México',
        'Guanajuato',
        'Guerrero',
        'Hidalgo',
        'Jalisco',
        'Michoacán',
        'Morelos',
        'Nayarit',
        'Nuevo León',
        'Oaxaca',
        'Puebla',
        'Querétaro',
        'Quintana Roo',
        'San Luis Potosí',
        'Sinaloa',
        'Sonora',
        'Tabasco',
        'Tamaulipas',
        'Tlaxcala',
        'Veracruz',
        'Yucatán',
        'Zacatecas',
    ],
    'slides' => [
        [
            'image' => '/img/productos/globos-slider.webp',
            'imageMobile' => '/img/productos/globos-movil-slider1.webp',
            'name' => '',
            'sku' => '',
            'description' => '',
            'alt' => 'Globos Sensacionales — Catalogo 2026',
            'href' => null,
        ],
        [
            'image' => '/img/productos/globos-slider2.webp',
            'imageMobile' => '/img/productos/globos-movil-slider2.webp',
            'name' => '',
            'sku' => '',
            'description' => '',
            'alt' => 'Globos Sensacionales — colección 2',
            'href' => null,
        ],
        [
            'image' => '/img/productos/globos-slider3.webp',
            'imageMobile' => '/img/productos/globos-movil-slider3.webp',
            'name' => '',
            'sku' => '',
            'description' => '',
            'alt' => 'Globos Sensacionales — colección 3',
            'href' => null,
        ],
        [
            'image' => '/img/productos/globos-slider4.webp',
            'imageMobile' => '/img/productos/globos-movil-slider4.webp',
            'name' => '',
            'sku' => '',
            'description' => '',
            'alt' => 'Globos Sensacionales — colección 4',
            'href' => null,
        ],
        [
            'image' => '/img/productos/globos-slider5.webp',
            'imageMobile' => '/img/productos/globos-movil-slider5.webp',
            'name' => '',
            'sku' => '',
            'description' => '',
            'alt' => 'Globos Sensacionales — colección 5',
            'href' => null,
        ],
    ],
];
