<?php

return [
    'name' => 'Globos Sensacionales',
    'shipping' => 'Envíos a todo México',
    'whatsapp' => env('GLOBOS_WHATSAPP', '5210000000000'),
    'whatsapp_message' => 'Hola, me interesa ser distribuidor de Globos Sensacionales y conocer sus productos. Envíos a todo México.',
    'catalog_path' => env('GLOBOS_CATALOG_PATH', 'catalogo/catalogo-sensacional.pdf'),
    'catalog_view_url' => '/catalogo/2026/Catalogo-Sensacional-2026.php',
    'social' => [
        'instagram' => env('GLOBOS_INSTAGRAM', 'https://www.instagram.com/globos_sensacional/'),
        'facebook' => env('GLOBOS_FACEBOOK', 'https://www.facebook.com/SensacionalGlobos'),
        'pinterest' => env('GLOBOS_PINTEREST', 'https://mx.pinterest.com/globossensacional/'),
        'tiktok' => env('GLOBOS_TIKTOK', 'https://www.tiktok.com/@globossensacional'),
        'youtube' => env('GLOBOS_YOUTUBE', 'https://www.youtube.com/@GlobosSensacional'),
    ],
    'seo' => [
        'description' => 'Globos Sensacionales fabrica globos 100% de látex natural para distribuidores, decoradores y puntos de venta. Más de 30 años de experiencia. Envíos a todo México.',
    ],
    'states' => [
        'Aguascalientes',
        'Baja California',
        'Baja California Sur',
        'Campeche',
        'Chiapas',
        'Chihuahua',
        'Ciudad de México',
        'Coahuila',
        'Colima',
        'Durango',
        'Estado de México',
        'Guanajuato',
        'Guerrero',
        'Hidalgo',
        'Jalisco',
        'Michoacán',
        'Morelos',
        'Nayarit',
        'Nuevo León',
        'Oaxaca',
        'Puebla',
        'Querétaro',
        'Quintana Roo',
        'San Luis Potosí',
        'Sinaloa',
        'Sonora',
        'Tabasco',
        'Tamaulipas',
        'Tlaxcala',
        'Veracruz',
        'Yucatán',
        'Zacatecas',
    ],
    'slides' => [
        [
            'image' => '/img/productos/slider1.webp',
            'name' => '',
            'sku' => '',
            'description' => '',
            'alt' => 'Catálogo de productos Sensacional 2026',
            'href' => '/catalogo/2026/Catalogo-Sensacional-2026.php',
        ],
    ],
];
